/* eslint-disable */
// Generated by scripts/optimize-images.js — do not edit by hand.

import { registerResponsiveImages } from '../../utils/responsiveImage';
import type { ResponsiveImageRecord } from '../../utils/responsiveImage';

import s0 from './camo.jpg';
import s0f0 from './camo.w480.jpg';
import s0f1 from './camo.w800.jpg';
import s0f2 from './camo.w960.jpg';
import s0w0 from './camo.w480.webp';
import s0w1 from './camo.w800.webp';
import s0w2 from './camo.w960.webp';
import s0a0 from './camo.w480.avif';
import s0a1 from './camo.w800.avif';
import s0a2 from './camo.w960.avif';

import s1 from './camo.png';
import s1f0 from './camo.png';
import s1w0 from './camo.w480.webp';
import s1w1 from './camo.w800.webp';
import s1w2 from './camo.w960.webp';
import s1a0 from './camo.w480.avif';
import s1a1 from './camo.w800.avif';
import s1a2 from './camo.w960.avif';

import s2 from './corn-kernals.png';
import s2f0 from './corn-kernals.png';
import s2w0 from './corn-kernals.w480.webp';
import s2w1 from './corn-kernals.w800.webp';
import s2w2 from './corn-kernals.w960.webp';
import s2a0 from './corn-kernals.w480.avif';
import s2a1 from './corn-kernals.w800.avif';
import s2a2 from './corn-kernals.w960.avif';

import s3 from './feeders/1n1/1n1.png';
import s3f0 from './feeders/1n1/1n1.png';
import s3w0 from './feeders/1n1/1n1.w480.webp';
import s3w1 from './feeders/1n1/1n1.w800.webp';
import s3w2 from './feeders/1n1/1n1.w926.webp';
import s3a0 from './feeders/1n1/1n1.w480.avif';
import s3a1 from './feeders/1n1/1n1.w800.avif';
import s3a2 from './feeders/1n1/1n1.w926.avif';

import s4 from './feeders/2n1/2n1.png';
import s4f0 from './feeders/2n1/2n1.png';
import s4w0 from './feeders/2n1/2n1.w478.webp';
import s4a0 from './feeders/2n1/2n1.w478.avif';

import s5 from './feeders/2n1/photos/1.jpg';
import s5f0 from './feeders/2n1/photos/1.w480.jpg';
import s5f1 from './feeders/2n1/photos/1.w800.jpg';
import s5f2 from './feeders/2n1/photos/1.w1067.jpg';
import s5w0 from './feeders/2n1/photos/1.w480.webp';
import s5w1 from './feeders/2n1/photos/1.w800.webp';
import s5w2 from './feeders/2n1/photos/1.w1067.webp';
import s5a0 from './feeders/2n1/photos/1.w480.avif';
import s5a1 from './feeders/2n1/photos/1.w800.avif';
import s5a2 from './feeders/2n1/photos/1.w1067.avif';

import s6 from './feeders/2n1/photos/2.jpg';
import s6f0 from './feeders/2n1/photos/2.w480.jpg';
import s6f1 from './feeders/2n1/photos/2.w800.jpg';
import s6f2 from './feeders/2n1/photos/2.w1200.jpg';
import s6f3 from './feeders/2n1/photos/2.w1600.jpg';
import s6w0 from './feeders/2n1/photos/2.w480.webp';
import s6w1 from './feeders/2n1/photos/2.w800.webp';
import s6w2 from './feeders/2n1/photos/2.w1200.webp';
import s6w3 from './feeders/2n1/photos/2.w1600.webp';
import s6a0 from './feeders/2n1/photos/2.w480.avif';
import s6a1 from './feeders/2n1/photos/2.w800.avif';
import s6a2 from './feeders/2n1/photos/2.w1200.avif';
import s6a3 from './feeders/2n1/photos/2.w1600.avif';

import s7 from './feeders/2n1/photos/3.jpg';
import s7f0 from './feeders/2n1/photos/3.w480.jpg';
import s7f1 from './feeders/2n1/photos/3.w800.jpg';
import s7f2 from './feeders/2n1/photos/3.w1200.jpg';
import s7f3 from './feeders/2n1/photos/3.w1335.jpg';
import s7w0 from './feeders/2n1/photos/3.w480.webp';
import s7w1 from './feeders/2n1/photos/3.w800.webp';
import s7w2 from './feeders/2n1/photos/3.w1200.webp';
import s7w3 from './feeders/2n1/photos/3.w1335.webp';
import s7a0 from './feeders/2n1/photos/3.w480.avif';
import s7a1 from './feeders/2n1/photos/3.w800.avif';
import s7a2 from './feeders/2n1/photos/3.w1200.avif';
import s7a3 from './feeders/2n1/photos/3.w1335.avif';

import s8 from './feeders/2n1/photos/4.jpg';
import s8f0 from './feeders/2n1/photos/4.w480.jpg';
import s8f1 from './feeders/2n1/photos/4.w800.jpg';
import s8f2 from './feeders/2n1/photos/4.w1200.jpg';
import s8f3 from './feeders/2n1/photos/4.w1600.jpg';
import s8w0 from './feeders/2n1/photos/4.w480.webp';
import s8w1 from './feeders/2n1/photos/4.w800.webp';
import s8w2 from './feeders/2n1/photos/4.w1200.webp';
import s8w3 from './feeders/2n1/photos/4.w1600.webp';
import s8a0 from './feeders/2n1/photos/4.w480.avif';
import s8a1 from './feeders/2n1/photos/4.w800.avif';
import s8a2 from './feeders/2n1/photos/4.w1200.avif';
import s8a3 from './feeders/2n1/photos/4.w1600.avif';

import s9 from './feeders/2n1/photos/5.jpg';
import s9f0 from './feeders/2n1/photos/5.w480.jpg';
import s9f1 from './feeders/2n1/photos/5.w800.jpg';
import s9f2 from './feeders/2n1/photos/5.w1200.jpg';
import s9f3 from './feeders/2n1/photos/5.w1600.jpg';
import s9w0 from './feeders/2n1/photos/5.w480.webp';
import s9w1 from './feeders/2n1/photos/5.w800.webp';
import s9w2 from './feeders/2n1/photos/5.w1200.webp';
import s9w3 from './feeders/2n1/photos/5.w1600.webp';
import s9a0 from './feeders/2n1/photos/5.w480.avif';
import s9a1 from './feeders/2n1/photos/5.w800.avif';
import s9a2 from './feeders/2n1/photos/5.w1200.avif';
import s9a3 from './feeders/2n1/photos/5.w1600.avif';

import s10 from './feeders/2n1/photos/6.jpg';
import s10f0 from './feeders/2n1/photos/6.w480.jpg';
import s10f1 from './feeders/2n1/photos/6.w800.jpg';
import s10f2 from './feeders/2n1/photos/6.w1044.jpg';
import s10w0 from './feeders/2n1/photos/6.w480.webp';
import s10w1 from './feeders/2n1/photos/6.w800.webp';
import s10w2 from './feeders/2n1/photos/6.w1044.webp';
import s10a0 from './feeders/2n1/photos/6.w480.avif';
import s10a1 from './feeders/2n1/photos/6.w800.avif';
import s10a2 from './feeders/2n1/photos/6.w1044.avif';

import s11 from './feeders/2n1/photos/7.jpg';
import s11f0 from './feeders/2n1/photos/7.w480.jpg';
import s11f1 from './feeders/2n1/photos/7.w800.jpg';
import s11f2 from './feeders/2n1/photos/7.w1067.jpg';
import s11w0 from './feeders/2n1/photos/7.w480.webp';
import s11w1 from './feeders/2n1/photos/7.w800.webp';
import s11w2 from './feeders/2n1/photos/7.w1067.webp';
import s11a0 from './feeders/2n1/photos/7.w480.avif';
import s11a1 from './feeders/2n1/photos/7.w800.avif';
import s11a2 from './feeders/2n1/photos/7.w1067.avif';

import s12 from './feeders/2n1/photos/8.jpg';
import s12f0 from './feeders/2n1/photos/8.w480.jpg';
import s12f1 from './feeders/2n1/photos/8.w800.jpg';
import s12f2 from './feeders/2n1/photos/8.w1200.jpg';
import s12f3 from './feeders/2n1/photos/8.w1600.jpg';
import s12w0 from './feeders/2n1/photos/8.w480.webp';
import s12w1 from './feeders/2n1/photos/8.w800.webp';
import s12w2 from './feeders/2n1/photos/8.w1200.webp';
import s12w3 from './feeders/2n1/photos/8.w1600.webp';
import s12a0 from './feeders/2n1/photos/8.w480.avif';
import s12a1 from './feeders/2n1/photos/8.w800.avif';
import s12a2 from './feeders/2n1/photos/8.w1200.avif';
import s12a3 from './feeders/2n1/photos/8.w1600.avif';

import s13 from './feeders/3n1/3n1.png';
import s13f0 from './feeders/3n1/3n1.png';
import s13w0 from './feeders/3n1/3n1.w480.webp';
import s13w1 from './feeders/3n1/3n1.w532.webp';
import s13a0 from './feeders/3n1/3n1.w480.avif';
import s13a1 from './feeders/3n1/3n1.w532.avif';

import s14 from './feeders/3n1/photos/1.jpg';
import s14f0 from './feeders/3n1/photos/1.w480.jpg';
import s14f1 from './feeders/3n1/photos/1.w800.jpg';
import s14f2 from './feeders/3n1/photos/1.w1067.jpg';
import s14w0 from './feeders/3n1/photos/1.w480.webp';
import s14w1 from './feeders/3n1/photos/1.w800.webp';
import s14w2 from './feeders/3n1/photos/1.w1067.webp';
import s14a0 from './feeders/3n1/photos/1.w480.avif';
import s14a1 from './feeders/3n1/photos/1.w800.avif';
import s14a2 from './feeders/3n1/photos/1.w1067.avif';

import s15 from './feeders/3n1/photos/2.jpg';
import s15f0 from './feeders/3n1/photos/2.w480.jpg';
import s15f1 from './feeders/3n1/photos/2.w800.jpg';
import s15f2 from './feeders/3n1/photos/2.w1200.jpg';
import s15f3 from './feeders/3n1/photos/2.w1600.jpg';
import s15w0 from './feeders/3n1/photos/2.w480.webp';
import s15w1 from './feeders/3n1/photos/2.w800.webp';
import s15w2 from './feeders/3n1/photos/2.w1200.webp';
import s15w3 from './feeders/3n1/photos/2.w1600.webp';
import s15a0 from './feeders/3n1/photos/2.w480.avif';
import s15a1 from './feeders/3n1/photos/2.w800.avif';
import s15a2 from './feeders/3n1/photos/2.w1200.avif';
import s15a3 from './feeders/3n1/photos/2.w1600.avif';

import s16 from './feeders/3n1/photos/3.jpg';
import s16f0 from './feeders/3n1/photos/3.w480.jpg';
import s16f1 from './feeders/3n1/photos/3.w800.jpg';
import s16f2 from './feeders/3n1/photos/3.w1200.jpg';
import s16f3 from './feeders/3n1/photos/3.w1335.jpg';
import s16w0 from './feeders/3n1/photos/3.w480.webp';
import s16w1 from './feeders/3n1/photos/3.w800.webp';
import s16w2 from './feeders/3n1/photos/3.w1200.webp';
import s16w3 from './feeders/3n1/photos/3.w1335.webp';
import s16a0 from './feeders/3n1/photos/3.w480.avif';
import s16a1 from './feeders/3n1/photos/3.w800.avif';
import s16a2 from './feeders/3n1/photos/3.w1200.avif';
import s16a3 from './feeders/3n1/photos/3.w1335.avif';

import s17 from './feeders/3n1/photos/4.jpg';
import s17f0 from './feeders/3n1/photos/4.w480.jpg';
import s17f1 from './feeders/3n1/photos/4.w800.jpg';
import s17f2 from './feeders/3n1/photos/4.w1200.jpg';
import s17f3 from './feeders/3n1/photos/4.w1600.jpg';
import s17w0 from './feeders/3n1/photos/4.w480.webp';
import s17w1 from './feeders/3n1/photos/4.w800.webp';
import s17w2 from './feeders/3n1/photos/4.w1200.webp';
import s17w3 from './feeders/3n1/photos/4.w1600.webp';
import s17a0 from './feeders/3n1/photos/4.w480.avif';
import s17a1 from './feeders/3n1/photos/4.w800.avif';
import s17a2 from './feeders/3n1/photos/4.w1200.avif';
import s17a3 from './feeders/3n1/photos/4.w1600.avif';

import s18 from './feeders/3n1/photos/5.jpg';
import s18f0 from './feeders/3n1/photos/5.w480.jpg';
import s18f1 from './feeders/3n1/photos/5.w800.jpg';
import s18f2 from './feeders/3n1/photos/5.w1200.jpg';
import s18f3 from './feeders/3n1/photos/5.w1600.jpg';
import s18w0 from './feeders/3n1/photos/5.w480.webp';
import s18w1 from './feeders/3n1/photos/5.w800.webp';
import s18w2 from './feeders/3n1/photos/5.w1200.webp';
import s18w3 from './feeders/3n1/photos/5.w1600.webp';
import s18a0 from './feeders/3n1/photos/5.w480.avif';
import s18a1 from './feeders/3n1/photos/5.w800.avif';
import s18a2 from './feeders/3n1/photos/5.w1200.avif';
import s18a3 from './feeders/3n1/photos/5.w1600.avif';

import s19 from './feeders/3n1/photos/6.jpg';
import s19f0 from './feeders/3n1/photos/6.w480.jpg';
import s19f1 from './feeders/3n1/photos/6.w800.jpg';
import s19f2 from './feeders/3n1/photos/6.w1044.jpg';
import s19w0 from './feeders/3n1/photos/6.w480.webp';
import s19w1 from './feeders/3n1/photos/6.w800.webp';
import s19w2 from './feeders/3n1/photos/6.w1044.webp';
import s19a0 from './feeders/3n1/photos/6.w480.avif';
import s19a1 from './feeders/3n1/photos/6.w800.avif';
import s19a2 from './feeders/3n1/photos/6.w1044.avif';

import s20 from './feeders/3n1/photos/7.jpg';
import s20f0 from './feeders/3n1/photos/7.w480.jpg';
import s20f1 from './feeders/3n1/photos/7.w800.jpg';
import s20f2 from './feeders/3n1/photos/7.w1067.jpg';
import s20w0 from './feeders/3n1/photos/7.w480.webp';
import s20w1 from './feeders/3n1/photos/7.w800.webp';
import s20w2 from './feeders/3n1/photos/7.w1067.webp';
import s20a0 from './feeders/3n1/photos/7.w480.avif';
import s20a1 from './feeders/3n1/photos/7.w800.avif';
import s20a2 from './feeders/3n1/photos/7.w1067.avif';

import s21 from './feeders/3n1/photos/8.jpg';
import s21f0 from './feeders/3n1/photos/8.w480.jpg';
import s21f1 from './feeders/3n1/photos/8.w800.jpg';
import s21f2 from './feeders/3n1/photos/8.w1200.jpg';
import s21f3 from './feeders/3n1/photos/8.w1600.jpg';
import s21w0 from './feeders/3n1/photos/8.w480.webp';
import s21w1 from './feeders/3n1/photos/8.w800.webp';
import s21w2 from './feeders/3n1/photos/8.w1200.webp';
import s21w3 from './feeders/3n1/photos/8.w1600.webp';
import s21a0 from './feeders/3n1/photos/8.w480.avif';
import s21a1 from './feeders/3n1/photos/8.w800.avif';
import s21a2 from './feeders/3n1/photos/8.w1200.avif';
import s21a3 from './feeders/3n1/photos/8.w1600.avif';

import s22 from './feeders/4n1/4n1.png';
import s22f0 from './feeders/4n1/4n1.png';
import s22w0 from './feeders/4n1/4n1.w480.webp';
import s22w1 from './feeders/4n1/4n1.w660.webp';
import s22a0 from './feeders/4n1/4n1.w480.avif';
import s22a1 from './feeders/4n1/4n1.w660.avif';

import s23 from './feeders/4n1/photos/1.jpg';
import s23f0 from './feeders/4n1/photos/1.w480.jpg';
import s23f1 from './feeders/4n1/photos/1.w800.jpg';
import s23f2 from './feeders/4n1/photos/1.w1067.jpg';
import s23w0 from './feeders/4n1/photos/1.w480.webp';
import s23w1 from './feeders/4n1/photos/1.w800.webp';
import s23w2 from './feeders/4n1/photos/1.w1067.webp';
import s23a0 from './feeders/4n1/photos/1.w480.avif';
import s23a1 from './feeders/4n1/photos/1.w800.avif';
import s23a2 from './feeders/4n1/photos/1.w1067.avif';

import s24 from './feeders/4n1/photos/2.jpg';
import s24f0 from './feeders/4n1/photos/2.w480.jpg';
import s24f1 from './feeders/4n1/photos/2.w800.jpg';
import s24f2 from './feeders/4n1/photos/2.w1200.jpg';
import s24f3 from './feeders/4n1/photos/2.w1600.jpg';
import s24w0 from './feeders/4n1/photos/2.w480.webp';
import s24w1 from './feeders/4n1/photos/2.w800.webp';
import s24w2 from './feeders/4n1/photos/2.w1200.webp';
import s24w3 from './feeders/4n1/photos/2.w1600.webp';
import s24a0 from './feeders/4n1/photos/2.w480.avif';
import s24a1 from './feeders/4n1/photos/2.w800.avif';
import s24a2 from './feeders/4n1/photos/2.w1200.avif';
import s24a3 from './feeders/4n1/photos/2.w1600.avif';

import s25 from './feeders/4n1/photos/3.jpg';
import s25f0 from './feeders/4n1/photos/3.w480.jpg';
import s25f1 from './feeders/4n1/photos/3.w800.jpg';
import s25f2 from './feeders/4n1/photos/3.w1200.jpg';
import s25f3 from './feeders/4n1/photos/3.w1335.jpg';
import s25w0 from './feeders/4n1/photos/3.w480.webp';
import s25w1 from './feeders/4n1/photos/3.w800.webp';
import s25w2 from './feeders/4n1/photos/3.w1200.webp';
import s25w3 from './feeders/4n1/photos/3.w1335.webp';
import s25a0 from './feeders/4n1/photos/3.w480.avif';
import s25a1 from './feeders/4n1/photos/3.w800.avif';
import s25a2 from './feeders/4n1/photos/3.w1200.avif';
import s25a3 from './feeders/4n1/photos/3.w1335.avif';

import s26 from './feeders/4n1/photos/4.jpg';
import s26f0 from './feeders/4n1/photos/4.w480.jpg';
import s26f1 from './feeders/4n1/photos/4.w800.jpg';
import s26f2 from './feeders/4n1/photos/4.w1200.jpg';
import s26f3 from './feeders/4n1/photos/4.w1600.jpg';
import s26w0 from './feeders/4n1/photos/4.w480.webp';
import s26w1 from './feeders/4n1/photos/4.w800.webp';
import s26w2 from './feeders/4n1/photos/4.w1200.webp';
import s26w3 from './feeders/4n1/photos/4.w1600.webp';
import s26a0 from './feeders/4n1/photos/4.w480.avif';
import s26a1 from './feeders/4n1/photos/4.w800.avif';
import s26a2 from './feeders/4n1/photos/4.w1200.avif';
import s26a3 from './feeders/4n1/photos/4.w1600.avif';

import s27 from './feeders/4n1/photos/5.jpg';
import s27f0 from './feeders/4n1/photos/5.w480.jpg';
import s27f1 from './feeders/4n1/photos/5.w800.jpg';
import s27f2 from './feeders/4n1/photos/5.w1200.jpg';
import s27f3 from './feeders/4n1/photos/5.w1600.jpg';
import s27w0 from './feeders/4n1/photos/5.w480.webp';
import s27w1 from './feeders/4n1/photos/5.w800.webp';
import s27w2 from './feeders/4n1/photos/5.w1200.webp';
import s27w3 from './feeders/4n1/photos/5.w1600.webp';
import s27a0 from './feeders/4n1/photos/5.w480.avif';
import s27a1 from './feeders/4n1/photos/5.w800.avif';
import s27a2 from './feeders/4n1/photos/5.w1200.avif';
import s27a3 from './feeders/4n1/photos/5.w1600.avif';

import s28 from './feeders/4n1/photos/6.jpg';
import s28f0 from './feeders/4n1/photos/6.w480.jpg';
import s28f1 from './feeders/4n1/photos/6.w800.jpg';
import s28f2 from './feeders/4n1/photos/6.w1044.jpg';
import s28w0 from './feeders/4n1/photos/6.w480.webp';
import s28w1 from './feeders/4n1/photos/6.w800.webp';
import s28w2 from './feeders/4n1/photos/6.w1044.webp';
import s28a0 from './feeders/4n1/photos/6.w480.avif';
import s28a1 from './feeders/4n1/photos/6.w800.avif';
import s28a2 from './feeders/4n1/photos/6.w1044.avif';

import s29 from './feeders/4n1/photos/7.jpg';
import s29f0 from './feeders/4n1/photos/7.w480.jpg';
import s29f1 from './feeders/4n1/photos/7.w800.jpg';
import s29f2 from './feeders/4n1/photos/7.w1067.jpg';
import s29w0 from './feeders/4n1/photos/7.w480.webp';
import s29w1 from './feeders/4n1/photos/7.w800.webp';
import s29w2 from './feeders/4n1/photos/7.w1067.webp';
import s29a0 from './feeders/4n1/photos/7.w480.avif';
import s29a1 from './feeders/4n1/photos/7.w800.avif';
import s29a2 from './feeders/4n1/photos/7.w1067.avif';

import s30 from './feeders/4n1/photos/8.jpg';
import s30f0 from './feeders/4n1/photos/8.w480.jpg';
import s30f1 from './feeders/4n1/photos/8.w800.jpg';
import s30f2 from './feeders/4n1/photos/8.w1200.jpg';
import s30f3 from './feeders/4n1/photos/8.w1600.jpg';
import s30w0 from './feeders/4n1/photos/8.w480.webp';
import s30w1 from './feeders/4n1/photos/8.w800.webp';
import s30w2 from './feeders/4n1/photos/8.w1200.webp';
import s30w3 from './feeders/4n1/photos/8.w1600.webp';
import s30a0 from './feeders/4n1/photos/8.w480.avif';
import s30a1 from './feeders/4n1/photos/8.w800.avif';
import s30a2 from './feeders/4n1/photos/8.w1200.avif';
import s30a3 from './feeders/4n1/photos/8.w1600.avif';

import s31 from './feeders/5n1/5n1.png';
import s31f0 from './feeders/5n1/5n1.png';
import s31w0 from './feeders/5n1/5n1.w480.webp';
import s31w1 from './feeders/5n1/5n1.w726.webp';
import s31a0 from './feeders/5n1/5n1.w480.avif';
import s31a1 from './feeders/5n1/5n1.w726.avif';

import s32 from './feeders/5n1/photos/1.jpg';
import s32f0 from './feeders/5n1/photos/1.w480.jpg';
import s32f1 from './feeders/5n1/photos/1.w800.jpg';
import s32f2 from './feeders/5n1/photos/1.w1067.jpg';
import s32w0 from './feeders/5n1/photos/1.w480.webp';
import s32w1 from './feeders/5n1/photos/1.w800.webp';
import s32w2 from './feeders/5n1/photos/1.w1067.webp';
import s32a0 from './feeders/5n1/photos/1.w480.avif';
import s32a1 from './feeders/5n1/photos/1.w800.avif';
import s32a2 from './feeders/5n1/photos/1.w1067.avif';

import s33 from './feeders/5n1/photos/2.jpg';
import s33f0 from './feeders/5n1/photos/2.w480.jpg';
import s33f1 from './feeders/5n1/photos/2.w800.jpg';
import s33f2 from './feeders/5n1/photos/2.w1200.jpg';
import s33f3 from './feeders/5n1/photos/2.w1600.jpg';
import s33w0 from './feeders/5n1/photos/2.w480.webp';
import s33w1 from './feeders/5n1/photos/2.w800.webp';
import s33w2 from './feeders/5n1/photos/2.w1200.webp';
import s33w3 from './feeders/5n1/photos/2.w1600.webp';
import s33a0 from './feeders/5n1/photos/2.w480.avif';
import s33a1 from './feeders/5n1/photos/2.w800.avif';
import s33a2 from './feeders/5n1/photos/2.w1200.avif';
import s33a3 from './feeders/5n1/photos/2.w1600.avif';

import s34 from './feeders/5n1/photos/3.jpg';
import s34f0 from './feeders/5n1/photos/3.w480.jpg';
import s34f1 from './feeders/5n1/photos/3.w800.jpg';
import s34f2 from './feeders/5n1/photos/3.w1200.jpg';
import s34f3 from './feeders/5n1/photos/3.w1335.jpg';
import s34w0 from './feeders/5n1/photos/3.w480.webp';
import s34w1 from './feeders/5n1/photos/3.w800.webp';
import s34w2 from './feeders/5n1/photos/3.w1200.webp';
import s34w3 from './feeders/5n1/photos/3.w1335.webp';
import s34a0 from './feeders/5n1/photos/3.w480.avif';
import s34a1 from './feeders/5n1/photos/3.w800.avif';
import s34a2 from './feeders/5n1/photos/3.w1200.avif';
import s34a3 from './feeders/5n1/photos/3.w1335.avif';

import s35 from './feeders/5n1/photos/4.jpg';
import s35f0 from './feeders/5n1/photos/4.w480.jpg';
import s35f1 from './feeders/5n1/photos/4.w800.jpg';
import s35f2 from './feeders/5n1/photos/4.w1200.jpg';
import s35f3 from './feeders/5n1/photos/4.w1600.jpg';
import s35w0 from './feeders/5n1/photos/4.w480.webp';
import s35w1 from './feeders/5n1/photos/4.w800.webp';
import s35w2 from './feeders/5n1/photos/4.w1200.webp';
import s35w3 from './feeders/5n1/photos/4.w1600.webp';
import s35a0 from './feeders/5n1/photos/4.w480.avif';
import s35a1 from './feeders/5n1/photos/4.w800.avif';
import s35a2 from './feeders/5n1/photos/4.w1200.avif';
import s35a3 from './feeders/5n1/photos/4.w1600.avif';

import s36 from './feeders/5n1/photos/5.jpg';
import s36f0 from './feeders/5n1/photos/5.w480.jpg';
import s36f1 from './feeders/5n1/photos/5.w800.jpg';
import s36f2 from './feeders/5n1/photos/5.w1200.jpg';
import s36f3 from './feeders/5n1/photos/5.w1600.jpg';
import s36w0 from './feeders/5n1/photos/5.w480.webp';
import s36w1 from './feeders/5n1/photos/5.w800.webp';
import s36w2 from './feeders/5n1/photos/5.w1200.webp';
import s36w3 from './feeders/5n1/photos/5.w1600.webp';
import s36a0 from './feeders/5n1/photos/5.w480.avif';
import s36a1 from './feeders/5n1/photos/5.w800.avif';
import s36a2 from './feeders/5n1/photos/5.w1200.avif';
import s36a3 from './feeders/5n1/photos/5.w1600.avif';

import s37 from './feeders/5n1/photos/6.jpg';
import s37f0 from './feeders/5n1/photos/6.w480.jpg';
import s37f1 from './feeders/5n1/photos/6.w800.jpg';
import s37f2 from './feeders/5n1/photos/6.w1044.jpg';
import s37w0 from './feeders/5n1/photos/6.w480.webp';
import s37w1 from './feeders/5n1/photos/6.w800.webp';
import s37w2 from './feeders/5n1/photos/6.w1044.webp';
import s37a0 from './feeders/5n1/photos/6.w480.avif';
import s37a1 from './feeders/5n1/photos/6.w800.avif';
import s37a2 from './feeders/5n1/photos/6.w1044.avif';

import s38 from './feeders/5n1/photos/7.jpg';
import s38f0 from './feeders/5n1/photos/7.w480.jpg';
import s38f1 from './feeders/5n1/photos/7.w800.jpg';
import s38f2 from './feeders/5n1/photos/7.w1067.jpg';
import s38w0 from './feeders/5n1/photos/7.w480.webp';
import s38w1 from './feeders/5n1/photos/7.w800.webp';
import s38w2 from './feeders/5n1/photos/7.w1067.webp';
import s38a0 from './feeders/5n1/photos/7.w480.avif';
import s38a1 from './feeders/5n1/photos/7.w800.avif';
import s38a2 from './feeders/5n1/photos/7.w1067.avif';

import s39 from './feeders/5n1/photos/8.jpg';
import s39f0 from './feeders/5n1/photos/8.w480.jpg';
import s39f1 from './feeders/5n1/photos/8.w800.jpg';
import s39f2 from './feeders/5n1/photos/8.w1200.jpg';
import s39f3 from './feeders/5n1/photos/8.w1600.jpg';
import s39w0 from './feeders/5n1/photos/8.w480.webp';
import s39w1 from './feeders/5n1/photos/8.w800.webp';
import s39w2 from './feeders/5n1/photos/8.w1200.webp';
import s39w3 from './feeders/5n1/photos/8.w1600.webp';
import s39a0 from './feeders/5n1/photos/8.w480.avif';
import s39a1 from './feeders/5n1/photos/8.w800.avif';
import s39a2 from './feeders/5n1/photos/8.w1200.avif';
import s39a3 from './feeders/5n1/photos/8.w1600.avif';

import s40 from './feeders/backyard/backyard.png';
import s40f0 from './feeders/backyard/backyard.png';
import s40w0 from './feeders/backyard/backyard.w480.webp';
import s40w1 from './feeders/backyard/backyard.w592.webp';
import s40a0 from './feeders/backyard/backyard.w480.avif';
import s40a1 from './feeders/backyard/backyard.w592.avif';

import s41 from './feeders/coveycafe/coveycafe.png';
import s41f0 from './feeders/coveycafe/coveycafe.png';
import s41w0 from './feeders/coveycafe/coveycafe.w480.webp';
import s41w1 from './feeders/coveycafe/coveycafe.w800.webp';
import s41a0 from './feeders/coveycafe/coveycafe.w480.avif';
import s41a1 from './feeders/coveycafe/coveycafe.w800.avif';

import s42 from './feeders/coveycafe/photos/1.jpg';
import s42f0 from './feeders/coveycafe/photos/1.w480.jpg';
import s42f1 from './feeders/coveycafe/photos/1.w600.jpg';
import s42w0 from './feeders/coveycafe/photos/1.w480.webp';
import s42w1 from './feeders/coveycafe/photos/1.w600.webp';
import s42a0 from './feeders/coveycafe/photos/1.w480.avif';
import s42a1 from './feeders/coveycafe/photos/1.w600.avif';

import s43 from './feeders/coveycafe/photos/2.jpg';
import s43f0 from './feeders/coveycafe/photos/2.w480.jpg';
import s43f1 from './feeders/coveycafe/photos/2.w800.jpg';
import s43w0 from './feeders/coveycafe/photos/2.w480.webp';
import s43w1 from './feeders/coveycafe/photos/2.w800.webp';
import s43a0 from './feeders/coveycafe/photos/2.w480.avif';
import s43a1 from './feeders/coveycafe/photos/2.w800.avif';

import s44 from './feeders/coveycafe/photos/3.jpg';
import s44f0 from './feeders/coveycafe/photos/3.w480.jpg';
import s44f1 from './feeders/coveycafe/photos/3.w800.jpg';
import s44w0 from './feeders/coveycafe/photos/3.w480.webp';
import s44w1 from './feeders/coveycafe/photos/3.w800.webp';
import s44a0 from './feeders/coveycafe/photos/3.w480.avif';
import s44a1 from './feeders/coveycafe/photos/3.w800.avif';

import s45 from './feeders/coveycafe/photos/4.jpg';
import s45f0 from './feeders/coveycafe/photos/4.w480.jpg';
import s45f1 from './feeders/coveycafe/photos/4.w800.jpg';
import s45w0 from './feeders/coveycafe/photos/4.w480.webp';
import s45w1 from './feeders/coveycafe/photos/4.w800.webp';
import s45a0 from './feeders/coveycafe/photos/4.w480.avif';
import s45a1 from './feeders/coveycafe/photos/4.w800.avif';

import s46 from './feeders/dockfeeder/dockfeeder.png';
import s46f0 from './feeders/dockfeeder/dockfeeder.png';
import s46w0 from './feeders/dockfeeder/dockfeeder.w480.webp';
import s46w1 from './feeders/dockfeeder/dockfeeder.w592.webp';
import s46a0 from './feeders/dockfeeder/dockfeeder.w480.avif';
import s46a1 from './feeders/dockfeeder/dockfeeder.w592.avif';

import s47 from './feeders/dockfeeder/photos/1.jpg';
import s47f0 from './feeders/dockfeeder/photos/1.w480.jpg';
import s47f1 from './feeders/dockfeeder/photos/1.w800.jpg';
import s47f2 from './feeders/dockfeeder/photos/1.w1200.jpg';
import s47w0 from './feeders/dockfeeder/photos/1.w480.webp';
import s47w1 from './feeders/dockfeeder/photos/1.w800.webp';
import s47w2 from './feeders/dockfeeder/photos/1.w1200.webp';
import s47a0 from './feeders/dockfeeder/photos/1.w480.avif';
import s47a1 from './feeders/dockfeeder/photos/1.w800.avif';
import s47a2 from './feeders/dockfeeder/photos/1.w1200.avif';

import s48 from './feeders/dueltray/dueltray.png';
import s48f0 from './feeders/dueltray/dueltray.png';
import s48w0 from './feeders/dueltray/dueltray.w480.webp';
import s48w1 from './feeders/dueltray/dueltray.w532.webp';
import s48a0 from './feeders/dueltray/dueltray.w480.avif';
import s48a1 from './feeders/dueltray/dueltray.w532.avif';

import s49 from './feeders/ricebrand/photos/1.jpg';
import s49f0 from './feeders/ricebrand/photos/1.w480.jpg';
import s49f1 from './feeders/ricebrand/photos/1.w600.jpg';
import s49w0 from './feeders/ricebrand/photos/1.w480.webp';
import s49w1 from './feeders/ricebrand/photos/1.w600.webp';
import s49a0 from './feeders/ricebrand/photos/1.w480.avif';
import s49a1 from './feeders/ricebrand/photos/1.w600.avif';

import s50 from './feeders/ricebrand/photos/2.jpg';
import s50f0 from './feeders/ricebrand/photos/2.w480.jpg';
import s50f1 from './feeders/ricebrand/photos/2.w800.jpg';
import s50f2 from './feeders/ricebrand/photos/2.w1067.jpg';
import s50w0 from './feeders/ricebrand/photos/2.w480.webp';
import s50w1 from './feeders/ricebrand/photos/2.w800.webp';
import s50w2 from './feeders/ricebrand/photos/2.w1067.webp';
import s50a0 from './feeders/ricebrand/photos/2.w480.avif';
import s50a1 from './feeders/ricebrand/photos/2.w800.avif';
import s50a2 from './feeders/ricebrand/photos/2.w1067.avif';

import s51 from './feeders/ricebrand/photos/3.jpg';
import s51f0 from './feeders/ricebrand/photos/3.w480.jpg';
import s51f1 from './feeders/ricebrand/photos/3.w800.jpg';
import s51f2 from './feeders/ricebrand/photos/3.w1067.jpg';
import s51w0 from './feeders/ricebrand/photos/3.w480.webp';
import s51w1 from './feeders/ricebrand/photos/3.w800.webp';
import s51w2 from './feeders/ricebrand/photos/3.w1067.webp';
import s51a0 from './feeders/ricebrand/photos/3.w480.avif';
import s51a1 from './feeders/ricebrand/photos/3.w800.avif';
import s51a2 from './feeders/ricebrand/photos/3.w1067.avif';

import s52 from './feeders/ricebrand/photos/4.jpg';
import s52f0 from './feeders/ricebrand/photos/4.w480.jpg';
import s52f1 from './feeders/ricebrand/photos/4.w800.jpg';
import s52f2 from './feeders/ricebrand/photos/4.w1200.jpg';
import s52f3 from './feeders/ricebrand/photos/4.w1600.jpg';
import s52w0 from './feeders/ricebrand/photos/4.w480.webp';
import s52w1 from './feeders/ricebrand/photos/4.w800.webp';
import s52w2 from './feeders/ricebrand/photos/4.w1200.webp';
import s52w3 from './feeders/ricebrand/photos/4.w1600.webp';
import s52a0 from './feeders/ricebrand/photos/4.w480.avif';
import s52a1 from './feeders/ricebrand/photos/4.w800.avif';
import s52a2 from './feeders/ricebrand/photos/4.w1200.avif';
import s52a3 from './feeders/ricebrand/photos/4.w1600.avif';

import s53 from './feeders/ricebrand/photos/5.jpg';
import s53f0 from './feeders/ricebrand/photos/5.w480.jpg';
import s53f1 from './feeders/ricebrand/photos/5.w800.jpg';
import s53f2 from './feeders/ricebrand/photos/5.w1200.jpg';
import s53f3 from './feeders/ricebrand/photos/5.w1600.jpg';
import s53w0 from './feeders/ricebrand/photos/5.w480.webp';
import s53w1 from './feeders/ricebrand/photos/5.w800.webp';
import s53w2 from './feeders/ricebrand/photos/5.w1200.webp';
import s53w3 from './feeders/ricebrand/photos/5.w1600.webp';
import s53a0 from './feeders/ricebrand/photos/5.w480.avif';
import s53a1 from './feeders/ricebrand/photos/5.w800.avif';
import s53a2 from './feeders/ricebrand/photos/5.w1200.avif';
import s53a3 from './feeders/ricebrand/photos/5.w1600.avif';

import s54 from './feeders/ricebrand/photos/6.jpg';
import s54f0 from './feeders/ricebrand/photos/6.w480.jpg';
import s54f1 from './feeders/ricebrand/photos/6.w800.jpg';
import s54f2 from './feeders/ricebrand/photos/6.w1067.jpg';
import s54w0 from './feeders/ricebrand/photos/6.w480.webp';
import s54w1 from './feeders/ricebrand/photos/6.w800.webp';
import s54w2 from './feeders/ricebrand/photos/6.w1067.webp';
import s54a0 from './feeders/ricebrand/photos/6.w480.avif';
import s54a1 from './feeders/ricebrand/photos/6.w800.avif';
import s54a2 from './feeders/ricebrand/photos/6.w1067.avif';

import s55 from './feeders/ricebrand/photos/7.jpg';
import s55f0 from './feeders/ricebrand/photos/7.w480.jpg';
import s55f1 from './feeders/ricebrand/photos/7.w800.jpg';
import s55f2 from './feeders/ricebrand/photos/7.w1200.jpg';
import s55f3 from './feeders/ricebrand/photos/7.w1600.jpg';
import s55w0 from './feeders/ricebrand/photos/7.w480.webp';
import s55w1 from './feeders/ricebrand/photos/7.w800.webp';
import s55w2 from './feeders/ricebrand/photos/7.w1200.webp';
import s55w3 from './feeders/ricebrand/photos/7.w1600.webp';
import s55a0 from './feeders/ricebrand/photos/7.w480.avif';
import s55a1 from './feeders/ricebrand/photos/7.w800.avif';
import s55a2 from './feeders/ricebrand/photos/7.w1200.avif';
import s55a3 from './feeders/ricebrand/photos/7.w1600.avif';

import s56 from './feeders/ricebrand/ricebrand.png';
import s56f0 from './feeders/ricebrand/ricebrand.png';
import s56w0 from './feeders/ricebrand/ricebrand.w480.webp';
import s56w1 from './feeders/ricebrand/ricebrand.w800.webp';
import s56a0 from './feeders/ricebrand/ricebrand.w480.avif';
import s56a1 from './feeders/ricebrand/ricebrand.w800.avif';

import s57 from './feeders/woody/photos/1.jpg';
import s57f0 from './feeders/woody/photos/1.w480.jpg';
import s57f1 from './feeders/woody/photos/1.w800.jpg';
import s57f2 from './feeders/woody/photos/1.w1067.jpg';
import s57w0 from './feeders/woody/photos/1.w480.webp';
import s57w1 from './feeders/woody/photos/1.w800.webp';
import s57w2 from './feeders/woody/photos/1.w1067.webp';
import s57a0 from './feeders/woody/photos/1.w480.avif';
import s57a1 from './feeders/woody/photos/1.w800.avif';
import s57a2 from './feeders/woody/photos/1.w1067.avif';

import s58 from './feeders/woody/photos/2.jpg';
import s58f0 from './feeders/woody/photos/2.w480.jpg';
import s58f1 from './feeders/woody/photos/2.w800.jpg';
import s58f2 from './feeders/woody/photos/2.w1200.jpg';
import s58f3 from './feeders/woody/photos/2.w1600.jpg';
import s58w0 from './feeders/woody/photos/2.w480.webp';
import s58w1 from './feeders/woody/photos/2.w800.webp';
import s58w2 from './feeders/woody/photos/2.w1200.webp';
import s58w3 from './feeders/woody/photos/2.w1600.webp';
import s58a0 from './feeders/woody/photos/2.w480.avif';
import s58a1 from './feeders/woody/photos/2.w800.avif';
import s58a2 from './feeders/woody/photos/2.w1200.avif';
import s58a3 from './feeders/woody/photos/2.w1600.avif';

import s59 from './feeders/woody/photos/3.jpg';
import s59f0 from './feeders/woody/photos/3.w480.jpg';
import s59f1 from './feeders/woody/photos/3.w800.jpg';
import s59f2 from './feeders/woody/photos/3.w1200.jpg';
import s59f3 from './feeders/woody/photos/3.w1335.jpg';
import s59w0 from './feeders/woody/photos/3.w480.webp';
import s59w1 from './feeders/woody/photos/3.w800.webp';
import s59w2 from './feeders/woody/photos/3.w1200.webp';
import s59w3 from './feeders/woody/photos/3.w1335.webp';
import s59a0 from './feeders/woody/photos/3.w480.avif';
import s59a1 from './feeders/woody/photos/3.w800.avif';
import s59a2 from './feeders/woody/photos/3.w1200.avif';
import s59a3 from './feeders/woody/photos/3.w1335.avif';

import s60 from './feeders/woody/photos/4.jpg';
import s60f0 from './feeders/woody/photos/4.w480.jpg';
import s60f1 from './feeders/woody/photos/4.w800.jpg';
import s60f2 from './feeders/woody/photos/4.w1200.jpg';
import s60f3 from './feeders/woody/photos/4.w1600.jpg';
import s60w0 from './feeders/woody/photos/4.w480.webp';
import s60w1 from './feeders/woody/photos/4.w800.webp';
import s60w2 from './feeders/woody/photos/4.w1200.webp';
import s60w3 from './feeders/woody/photos/4.w1600.webp';
import s60a0 from './feeders/woody/photos/4.w480.avif';
import s60a1 from './feeders/woody/photos/4.w800.avif';
import s60a2 from './feeders/woody/photos/4.w1200.avif';
import s60a3 from './feeders/woody/photos/4.w1600.avif';

import s61 from './feeders/woody/photos/5.jpg';
import s61f0 from './feeders/woody/photos/5.w480.jpg';
import s61f1 from './feeders/woody/photos/5.w800.jpg';
import s61f2 from './feeders/woody/photos/5.w1200.jpg';
import s61f3 from './feeders/woody/photos/5.w1600.jpg';
import s61w0 from './feeders/woody/photos/5.w480.webp';
import s61w1 from './feeders/woody/photos/5.w800.webp';
import s61w2 from './feeders/woody/photos/5.w1200.webp';
import s61w3 from './feeders/woody/photos/5.w1600.webp';
import s61a0 from './feeders/woody/photos/5.w480.avif';
import s61a1 from './feeders/woody/photos/5.w800.avif';
import s61a2 from './feeders/woody/photos/5.w1200.avif';
import s61a3 from './feeders/woody/photos/5.w1600.avif';

import s62 from './feeders/woody/photos/6.jpg';
import s62f0 from './feeders/woody/photos/6.w480.jpg';
import s62f1 from './feeders/woody/photos/6.w800.jpg';
import s62f2 from './feeders/woody/photos/6.w1044.jpg';
import s62w0 from './feeders/woody/photos/6.w480.webp';
import s62w1 from './feeders/woody/photos/6.w800.webp';
import s62w2 from './feeders/woody/photos/6.w1044.webp';
import s62a0 from './feeders/woody/photos/6.w480.avif';
import s62a1 from './feeders/woody/photos/6.w800.avif';
import s62a2 from './feeders/woody/photos/6.w1044.avif';

import s63 from './feeders/woody/photos/7.jpg';
import s63f0 from './feeders/woody/photos/7.w480.jpg';
import s63f1 from './feeders/woody/photos/7.w800.jpg';
import s63f2 from './feeders/woody/photos/7.w1067.jpg';
import s63w0 from './feeders/woody/photos/7.w480.webp';
import s63w1 from './feeders/woody/photos/7.w800.webp';
import s63w2 from './feeders/woody/photos/7.w1067.webp';
import s63a0 from './feeders/woody/photos/7.w480.avif';
import s63a1 from './feeders/woody/photos/7.w800.avif';
import s63a2 from './feeders/woody/photos/7.w1067.avif';

import s64 from './feeders/woody/photos/8.jpg';
import s64f0 from './feeders/woody/photos/8.w480.jpg';
import s64f1 from './feeders/woody/photos/8.w800.jpg';
import s64f2 from './feeders/woody/photos/8.w1200.jpg';
import s64f3 from './feeders/woody/photos/8.w1600.jpg';
import s64w0 from './feeders/woody/photos/8.w480.webp';
import s64w1 from './feeders/woody/photos/8.w800.webp';
import s64w2 from './feeders/woody/photos/8.w1200.webp';
import s64w3 from './feeders/woody/photos/8.w1600.webp';
import s64a0 from './feeders/woody/photos/8.w480.avif';
import s64a1 from './feeders/woody/photos/8.w800.avif';
import s64a2 from './feeders/woody/photos/8.w1200.avif';
import s64a3 from './feeders/woody/photos/8.w1600.avif';

import s65 from './feeders/xxx/xxx.png';
import s65f0 from './feeders/xxx/xxx.png';
import s65w0 from './feeders/xxx/xxx.w480.webp';
import s65w1 from './feeders/xxx/xxx.w726.webp';
import s65a0 from './feeders/xxx/xxx.w480.avif';
import s65a1 from './feeders/xxx/xxx.w726.avif';

import s66 from './guard.jpg';
import s66f0 from './guard.w480.jpg';
import s66f1 from './guard.w800.jpg';
import s66f2 from './guard.w1200.jpg';
import s66f3 from './guard.w1600.jpg';
import s66w0 from './guard.w480.webp';
import s66w1 from './guard.w800.webp';
import s66w2 from './guard.w1200.webp';
import s66w3 from './guard.w1600.webp';
import s66a0 from './guard.w480.avif';
import s66a1 from './guard.w800.avif';
import s66a2 from './guard.w1200.avif';
import s66a3 from './guard.w1600.avif';

import s67 from './moose.png';
import s67f0 from './moose.png';
import s67w0 from './moose.w480.webp';
import s67w1 from './moose.w800.webp';
import s67w2 from './moose.w921.webp';
import s67a0 from './moose.w480.avif';
import s67a1 from './moose.w800.avif';
import s67a2 from './moose.w921.avif';

import s68 from './rice-brand-feeder.png';
import s68f0 from './rice-brand-feeder.png';
import s68w0 from './rice-brand-feeder.w480.webp';
import s68w1 from './rice-brand-feeder.w800.webp';
import s68w2 from './rice-brand-feeder.w960.webp';
import s68a0 from './rice-brand-feeder.w480.avif';
import s68a1 from './rice-brand-feeder.w800.avif';
import s68a2 from './rice-brand-feeder.w960.avif';

import s69 from './solarPanel1.png';
import s69f0 from './solarPanel1.png';
import s69w0 from './solarPanel1.w480.webp';
import s69w1 from './solarPanel1.w759.webp';
import s69a0 from './solarPanel1.w480.avif';
import s69a1 from './solarPanel1.w759.avif';

import s70 from './solarPanel2.png';
import s70f0 from './solarPanel2.png';
import s70w0 from './solarPanel2.w480.webp';
import s70w1 from './solarPanel2.w791.webp';
import s70a0 from './solarPanel2.w480.avif';
import s70a1 from './solarPanel2.w791.avif';

import s71 from './special-ops/photos/full/6.jpg';
import s71f0 from './special-ops/photos/full/6.w480.jpg';
import s71f1 from './special-ops/photos/full/6.w800.jpg';
import s71f2 from './special-ops/photos/full/6.w1200.jpg';
import s71f3 from './special-ops/photos/full/6.w1600.jpg';
import s71w0 from './special-ops/photos/full/6.w480.webp';
import s71w1 from './special-ops/photos/full/6.w800.webp';
import s71w2 from './special-ops/photos/full/6.w1200.webp';
import s71w3 from './special-ops/photos/full/6.w1600.webp';
import s71a0 from './special-ops/photos/full/6.w480.avif';
import s71a1 from './special-ops/photos/full/6.w800.avif';
import s71a2 from './special-ops/photos/full/6.w1200.avif';
import s71a3 from './special-ops/photos/full/6.w1600.avif';

import s72 from './testimonials/alex.jpg';
import s72f0 from './testimonials/alex.w480.jpg';
import s72f1 from './testimonials/alex.w500.jpg';
import s72w0 from './testimonials/alex.w480.webp';
import s72w1 from './testimonials/alex.w500.webp';
import s72a0 from './testimonials/alex.w480.avif';
import s72a1 from './testimonials/alex.w500.avif';

import s73 from './testimonials/eric.jpg';
import s73f0 from './testimonials/eric.w480.jpg';
import s73f1 from './testimonials/eric.w500.jpg';
import s73w0 from './testimonials/eric.w480.webp';
import s73w1 from './testimonials/eric.w500.webp';
import s73a0 from './testimonials/eric.w480.avif';
import s73a1 from './testimonials/eric.w500.avif';

import s74 from './testimonials/steve.jpg';
import s74f0 from './testimonials/steve.w480.jpg';
import s74f1 from './testimonials/steve.w500.jpg';
import s74w0 from './testimonials/steve.w480.webp';
import s74w1 from './testimonials/steve.w500.webp';
import s74a0 from './testimonials/steve.w480.avif';
import s74a1 from './testimonials/steve.w500.avif';

import s75 from './tree-hugger/massxl-feed.png';
import s75f0 from './tree-hugger/massxl-feed.png';
import s75w0 from './tree-hugger/massxl-feed.w480.webp';
import s75w1 from './tree-hugger/massxl-feed.w600.webp';
import s75a0 from './tree-hugger/massxl-feed.w480.avif';
import s75a1 from './tree-hugger/massxl-feed.w600.avif';

import s76 from './viewport.png';
import s76f0 from './viewport.png';
import s76w0 from './viewport.w480.webp';
import s76w1 from './viewport.w704.webp';
import s76a0 from './viewport.w480.avif';
import s76a1 from './viewport.w704.avif';

const records: ResponsiveImageRecord[] = [
  {
    src: s0,
    width: 960,
    height: 1080,
    fallbackSrcSet: `${s0f0} 480w, ${s0f1} 800w, ${s0f2} 960w`,
    webpSrcSet: `${s0w0} 480w, ${s0w1} 800w, ${s0w2} 960w`,
    avifSrcSet: `${s0a0} 480w, ${s0a1} 800w, ${s0a2} 960w`,
  },
  {
    src: s1,
    width: 960,
    height: 1080,
    fallbackSrcSet: `${s1f0} 960w`,
    webpSrcSet: `${s1w0} 480w, ${s1w1} 800w, ${s1w2} 960w`,
    avifSrcSet: `${s1a0} 480w, ${s1a1} 800w, ${s1a2} 960w`,
  },
  {
    src: s2,
    width: 960,
    height: 1080,
    fallbackSrcSet: `${s2f0} 960w`,
    webpSrcSet: `${s2w0} 480w, ${s2w1} 800w, ${s2w2} 960w`,
    avifSrcSet: `${s2a0} 480w, ${s2a1} 800w, ${s2a2} 960w`,
  },
  {
    src: s3,
    width: 926,
    height: 1392,
    fallbackSrcSet: `${s3f0} 926w`,
    webpSrcSet: `${s3w0} 480w, ${s3w1} 800w, ${s3w2} 926w`,
    avifSrcSet: `${s3a0} 480w, ${s3a1} 800w, ${s3a2} 926w`,
  },
  {
    src: s4,
    width: 478,
    height: 801,
    fallbackSrcSet: `${s4f0} 478w`,
    webpSrcSet: `${s4w0} 478w`,
    avifSrcSet: `${s4a0} 478w`,
  },
  {
    src: s5,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s5f0} 480w, ${s5f1} 800w, ${s5f2} 1067w`,
    webpSrcSet: `${s5w0} 480w, ${s5w1} 800w, ${s5w2} 1067w`,
    avifSrcSet: `${s5a0} 480w, ${s5a1} 800w, ${s5a2} 1067w`,
  },
  {
    src: s6,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s6f0} 480w, ${s6f1} 800w, ${s6f2} 1200w, ${s6f3} 1600w`,
    webpSrcSet: `${s6w0} 480w, ${s6w1} 800w, ${s6w2} 1200w, ${s6w3} 1600w`,
    avifSrcSet: `${s6a0} 480w, ${s6a1} 800w, ${s6a2} 1200w, ${s6a3} 1600w`,
  },
  {
    src: s7,
    width: 1335,
    height: 1392,
    fallbackSrcSet: `${s7f0} 480w, ${s7f1} 800w, ${s7f2} 1200w, ${s7f3} 1335w`,
    webpSrcSet: `${s7w0} 480w, ${s7w1} 800w, ${s7w2} 1200w, ${s7w3} 1335w`,
    avifSrcSet: `${s7a0} 480w, ${s7a1} 800w, ${s7a2} 1200w, ${s7a3} 1335w`,
  },
  {
    src: s8,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s8f0} 480w, ${s8f1} 800w, ${s8f2} 1200w, ${s8f3} 1600w`,
    webpSrcSet: `${s8w0} 480w, ${s8w1} 800w, ${s8w2} 1200w, ${s8w3} 1600w`,
    avifSrcSet: `${s8a0} 480w, ${s8a1} 800w, ${s8a2} 1200w, ${s8a3} 1600w`,
  },
  {
    src: s9,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s9f0} 480w, ${s9f1} 800w, ${s9f2} 1200w, ${s9f3} 1600w`,
    webpSrcSet: `${s9w0} 480w, ${s9w1} 800w, ${s9w2} 1200w, ${s9w3} 1600w`,
    avifSrcSet: `${s9a0} 480w, ${s9a1} 800w, ${s9a2} 1200w, ${s9a3} 1600w`,
  },
  {
    src: s10,
    width: 1044,
    height: 1392,
    fallbackSrcSet: `${s10f0} 480w, ${s10f1} 800w, ${s10f2} 1044w`,
    webpSrcSet: `${s10w0} 480w, ${s10w1} 800w, ${s10w2} 1044w`,
    avifSrcSet: `${s10a0} 480w, ${s10a1} 800w, ${s10a2} 1044w`,
  },
  {
    src: s11,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s11f0} 480w, ${s11f1} 800w, ${s11f2} 1067w`,
    webpSrcSet: `${s11w0} 480w, ${s11w1} 800w, ${s11w2} 1067w`,
    avifSrcSet: `${s11a0} 480w, ${s11a1} 800w, ${s11a2} 1067w`,
  },
  {
    src: s12,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s12f0} 480w, ${s12f1} 800w, ${s12f2} 1200w, ${s12f3} 1600w`,
    webpSrcSet: `${s12w0} 480w, ${s12w1} 800w, ${s12w2} 1200w, ${s12w3} 1600w`,
    avifSrcSet: `${s12a0} 480w, ${s12a1} 800w, ${s12a2} 1200w, ${s12a3} 1600w`,
  },
  {
    src: s13,
    width: 532,
    height: 800,
    fallbackSrcSet: `${s13f0} 532w`,
    webpSrcSet: `${s13w0} 480w, ${s13w1} 532w`,
    avifSrcSet: `${s13a0} 480w, ${s13a1} 532w`,
  },
  {
    src: s14,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s14f0} 480w, ${s14f1} 800w, ${s14f2} 1067w`,
    webpSrcSet: `${s14w0} 480w, ${s14w1} 800w, ${s14w2} 1067w`,
    avifSrcSet: `${s14a0} 480w, ${s14a1} 800w, ${s14a2} 1067w`,
  },
  {
    src: s15,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s15f0} 480w, ${s15f1} 800w, ${s15f2} 1200w, ${s15f3} 1600w`,
    webpSrcSet: `${s15w0} 480w, ${s15w1} 800w, ${s15w2} 1200w, ${s15w3} 1600w`,
    avifSrcSet: `${s15a0} 480w, ${s15a1} 800w, ${s15a2} 1200w, ${s15a3} 1600w`,
  },
  {
    src: s16,
    width: 1335,
    height: 1392,
    fallbackSrcSet: `${s16f0} 480w, ${s16f1} 800w, ${s16f2} 1200w, ${s16f3} 1335w`,
    webpSrcSet: `${s16w0} 480w, ${s16w1} 800w, ${s16w2} 1200w, ${s16w3} 1335w`,
    avifSrcSet: `${s16a0} 480w, ${s16a1} 800w, ${s16a2} 1200w, ${s16a3} 1335w`,
  },
  {
    src: s17,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s17f0} 480w, ${s17f1} 800w, ${s17f2} 1200w, ${s17f3} 1600w`,
    webpSrcSet: `${s17w0} 480w, ${s17w1} 800w, ${s17w2} 1200w, ${s17w3} 1600w`,
    avifSrcSet: `${s17a0} 480w, ${s17a1} 800w, ${s17a2} 1200w, ${s17a3} 1600w`,
  },
  {
    src: s18,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s18f0} 480w, ${s18f1} 800w, ${s18f2} 1200w, ${s18f3} 1600w`,
    webpSrcSet: `${s18w0} 480w, ${s18w1} 800w, ${s18w2} 1200w, ${s18w3} 1600w`,
    avifSrcSet: `${s18a0} 480w, ${s18a1} 800w, ${s18a2} 1200w, ${s18a3} 1600w`,
  },
  {
    src: s19,
    width: 1044,
    height: 1392,
    fallbackSrcSet: `${s19f0} 480w, ${s19f1} 800w, ${s19f2} 1044w`,
    webpSrcSet: `${s19w0} 480w, ${s19w1} 800w, ${s19w2} 1044w`,
    avifSrcSet: `${s19a0} 480w, ${s19a1} 800w, ${s19a2} 1044w`,
  },
  {
    src: s20,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s20f0} 480w, ${s20f1} 800w, ${s20f2} 1067w`,
    webpSrcSet: `${s20w0} 480w, ${s20w1} 800w, ${s20w2} 1067w`,
    avifSrcSet: `${s20a0} 480w, ${s20a1} 800w, ${s20a2} 1067w`,
  },
  {
    src: s21,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s21f0} 480w, ${s21f1} 800w, ${s21f2} 1200w, ${s21f3} 1600w`,
    webpSrcSet: `${s21w0} 480w, ${s21w1} 800w, ${s21w2} 1200w, ${s21w3} 1600w`,
    avifSrcSet: `${s21a0} 480w, ${s21a1} 800w, ${s21a2} 1200w, ${s21a3} 1600w`,
  },
  {
    src: s22,
    width: 660,
    height: 800,
    fallbackSrcSet: `${s22f0} 660w`,
    webpSrcSet: `${s22w0} 480w, ${s22w1} 660w`,
    avifSrcSet: `${s22a0} 480w, ${s22a1} 660w`,
  },
  {
    src: s23,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s23f0} 480w, ${s23f1} 800w, ${s23f2} 1067w`,
    webpSrcSet: `${s23w0} 480w, ${s23w1} 800w, ${s23w2} 1067w`,
    avifSrcSet: `${s23a0} 480w, ${s23a1} 800w, ${s23a2} 1067w`,
  },
  {
    src: s24,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s24f0} 480w, ${s24f1} 800w, ${s24f2} 1200w, ${s24f3} 1600w`,
    webpSrcSet: `${s24w0} 480w, ${s24w1} 800w, ${s24w2} 1200w, ${s24w3} 1600w`,
    avifSrcSet: `${s24a0} 480w, ${s24a1} 800w, ${s24a2} 1200w, ${s24a3} 1600w`,
  },
  {
    src: s25,
    width: 1335,
    height: 1392,
    fallbackSrcSet: `${s25f0} 480w, ${s25f1} 800w, ${s25f2} 1200w, ${s25f3} 1335w`,
    webpSrcSet: `${s25w0} 480w, ${s25w1} 800w, ${s25w2} 1200w, ${s25w3} 1335w`,
    avifSrcSet: `${s25a0} 480w, ${s25a1} 800w, ${s25a2} 1200w, ${s25a3} 1335w`,
  },
  {
    src: s26,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s26f0} 480w, ${s26f1} 800w, ${s26f2} 1200w, ${s26f3} 1600w`,
    webpSrcSet: `${s26w0} 480w, ${s26w1} 800w, ${s26w2} 1200w, ${s26w3} 1600w`,
    avifSrcSet: `${s26a0} 480w, ${s26a1} 800w, ${s26a2} 1200w, ${s26a3} 1600w`,
  },
  {
    src: s27,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s27f0} 480w, ${s27f1} 800w, ${s27f2} 1200w, ${s27f3} 1600w`,
    webpSrcSet: `${s27w0} 480w, ${s27w1} 800w, ${s27w2} 1200w, ${s27w3} 1600w`,
    avifSrcSet: `${s27a0} 480w, ${s27a1} 800w, ${s27a2} 1200w, ${s27a3} 1600w`,
  },
  {
    src: s28,
    width: 1044,
    height: 1392,
    fallbackSrcSet: `${s28f0} 480w, ${s28f1} 800w, ${s28f2} 1044w`,
    webpSrcSet: `${s28w0} 480w, ${s28w1} 800w, ${s28w2} 1044w`,
    avifSrcSet: `${s28a0} 480w, ${s28a1} 800w, ${s28a2} 1044w`,
  },
  {
    src: s29,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s29f0} 480w, ${s29f1} 800w, ${s29f2} 1067w`,
    webpSrcSet: `${s29w0} 480w, ${s29w1} 800w, ${s29w2} 1067w`,
    avifSrcSet: `${s29a0} 480w, ${s29a1} 800w, ${s29a2} 1067w`,
  },
  {
    src: s30,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s30f0} 480w, ${s30f1} 800w, ${s30f2} 1200w, ${s30f3} 1600w`,
    webpSrcSet: `${s30w0} 480w, ${s30w1} 800w, ${s30w2} 1200w, ${s30w3} 1600w`,
    avifSrcSet: `${s30a0} 480w, ${s30a1} 800w, ${s30a2} 1200w, ${s30a3} 1600w`,
  },
  {
    src: s31,
    width: 726,
    height: 800,
    fallbackSrcSet: `${s31f0} 726w`,
    webpSrcSet: `${s31w0} 480w, ${s31w1} 726w`,
    avifSrcSet: `${s31a0} 480w, ${s31a1} 726w`,
  },
  {
    src: s32,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s32f0} 480w, ${s32f1} 800w, ${s32f2} 1067w`,
    webpSrcSet: `${s32w0} 480w, ${s32w1} 800w, ${s32w2} 1067w`,
    avifSrcSet: `${s32a0} 480w, ${s32a1} 800w, ${s32a2} 1067w`,
  },
  {
    src: s33,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s33f0} 480w, ${s33f1} 800w, ${s33f2} 1200w, ${s33f3} 1600w`,
    webpSrcSet: `${s33w0} 480w, ${s33w1} 800w, ${s33w2} 1200w, ${s33w3} 1600w`,
    avifSrcSet: `${s33a0} 480w, ${s33a1} 800w, ${s33a2} 1200w, ${s33a3} 1600w`,
  },
  {
    src: s34,
    width: 1335,
    height: 1392,
    fallbackSrcSet: `${s34f0} 480w, ${s34f1} 800w, ${s34f2} 1200w, ${s34f3} 1335w`,
    webpSrcSet: `${s34w0} 480w, ${s34w1} 800w, ${s34w2} 1200w, ${s34w3} 1335w`,
    avifSrcSet: `${s34a0} 480w, ${s34a1} 800w, ${s34a2} 1200w, ${s34a3} 1335w`,
  },
  {
    src: s35,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s35f0} 480w, ${s35f1} 800w, ${s35f2} 1200w, ${s35f3} 1600w`,
    webpSrcSet: `${s35w0} 480w, ${s35w1} 800w, ${s35w2} 1200w, ${s35w3} 1600w`,
    avifSrcSet: `${s35a0} 480w, ${s35a1} 800w, ${s35a2} 1200w, ${s35a3} 1600w`,
  },
  {
    src: s36,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s36f0} 480w, ${s36f1} 800w, ${s36f2} 1200w, ${s36f3} 1600w`,
    webpSrcSet: `${s36w0} 480w, ${s36w1} 800w, ${s36w2} 1200w, ${s36w3} 1600w`,
    avifSrcSet: `${s36a0} 480w, ${s36a1} 800w, ${s36a2} 1200w, ${s36a3} 1600w`,
  },
  {
    src: s37,
    width: 1044,
    height: 1392,
    fallbackSrcSet: `${s37f0} 480w, ${s37f1} 800w, ${s37f2} 1044w`,
    webpSrcSet: `${s37w0} 480w, ${s37w1} 800w, ${s37w2} 1044w`,
    avifSrcSet: `${s37a0} 480w, ${s37a1} 800w, ${s37a2} 1044w`,
  },
  {
    src: s38,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s38f0} 480w, ${s38f1} 800w, ${s38f2} 1067w`,
    webpSrcSet: `${s38w0} 480w, ${s38w1} 800w, ${s38w2} 1067w`,
    avifSrcSet: `${s38a0} 480w, ${s38a1} 800w, ${s38a2} 1067w`,
  },
  {
    src: s39,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s39f0} 480w, ${s39f1} 800w, ${s39f2} 1200w, ${s39f3} 1600w`,
    webpSrcSet: `${s39w0} 480w, ${s39w1} 800w, ${s39w2} 1200w, ${s39w3} 1600w`,
    avifSrcSet: `${s39a0} 480w, ${s39a1} 800w, ${s39a2} 1200w, ${s39a3} 1600w`,
  },
  {
    src: s40,
    width: 592,
    height: 808,
    fallbackSrcSet: `${s40f0} 592w`,
    webpSrcSet: `${s40w0} 480w, ${s40w1} 592w`,
    avifSrcSet: `${s40a0} 480w, ${s40a1} 592w`,
  },
  {
    src: s41,
    width: 800,
    height: 600,
    fallbackSrcSet: `${s41f0} 800w`,
    webpSrcSet: `${s41w0} 480w, ${s41w1} 800w`,
    avifSrcSet: `${s41a0} 480w, ${s41a1} 800w`,
  },
  {
    src: s42,
    width: 600,
    height: 800,
    fallbackSrcSet: `${s42f0} 480w, ${s42f1} 600w`,
    webpSrcSet: `${s42w0} 480w, ${s42w1} 600w`,
    avifSrcSet: `${s42a0} 480w, ${s42a1} 600w`,
  },
  {
    src: s43,
    width: 800,
    height: 600,
    fallbackSrcSet: `${s43f0} 480w, ${s43f1} 800w`,
    webpSrcSet: `${s43w0} 480w, ${s43w1} 800w`,
    avifSrcSet: `${s43a0} 480w, ${s43a1} 800w`,
  },
  {
    src: s44,
    width: 800,
    height: 600,
    fallbackSrcSet: `${s44f0} 480w, ${s44f1} 800w`,
    webpSrcSet: `${s44w0} 480w, ${s44w1} 800w`,
    avifSrcSet: `${s44a0} 480w, ${s44a1} 800w`,
  },
  {
    src: s45,
    width: 800,
    height: 600,
    fallbackSrcSet: `${s45f0} 480w, ${s45f1} 800w`,
    webpSrcSet: `${s45w0} 480w, ${s45w1} 800w`,
    avifSrcSet: `${s45a0} 480w, ${s45a1} 800w`,
  },
  {
    src: s46,
    width: 592,
    height: 778,
    fallbackSrcSet: `${s46f0} 592w`,
    webpSrcSet: `${s46w0} 480w, ${s46w1} 592w`,
    avifSrcSet: `${s46a0} 480w, ${s46a1} 592w`,
  },
  {
    src: s47,
    width: 1200,
    height: 1600,
    fallbackSrcSet: `${s47f0} 480w, ${s47f1} 800w, ${s47f2} 1200w`,
    webpSrcSet: `${s47w0} 480w, ${s47w1} 800w, ${s47w2} 1200w`,
    avifSrcSet: `${s47a0} 480w, ${s47a1} 800w, ${s47a2} 1200w`,
  },
  {
    src: s48,
    width: 532,
    height: 800,
    fallbackSrcSet: `${s48f0} 532w`,
    webpSrcSet: `${s48w0} 480w, ${s48w1} 532w`,
    avifSrcSet: `${s48a0} 480w, ${s48a1} 532w`,
  },
  {
    src: s49,
    width: 600,
    height: 800,
    fallbackSrcSet: `${s49f0} 480w, ${s49f1} 600w`,
    webpSrcSet: `${s49w0} 480w, ${s49w1} 600w`,
    avifSrcSet: `${s49a0} 480w, ${s49a1} 600w`,
  },
  {
    src: s50,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s50f0} 480w, ${s50f1} 800w, ${s50f2} 1067w`,
    webpSrcSet: `${s50w0} 480w, ${s50w1} 800w, ${s50w2} 1067w`,
    avifSrcSet: `${s50a0} 480w, ${s50a1} 800w, ${s50a2} 1067w`,
  },
  {
    src: s51,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s51f0} 480w, ${s51f1} 800w, ${s51f2} 1067w`,
    webpSrcSet: `${s51w0} 480w, ${s51w1} 800w, ${s51w2} 1067w`,
    avifSrcSet: `${s51a0} 480w, ${s51a1} 800w, ${s51a2} 1067w`,
  },
  {
    src: s52,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s52f0} 480w, ${s52f1} 800w, ${s52f2} 1200w, ${s52f3} 1600w`,
    webpSrcSet: `${s52w0} 480w, ${s52w1} 800w, ${s52w2} 1200w, ${s52w3} 1600w`,
    avifSrcSet: `${s52a0} 480w, ${s52a1} 800w, ${s52a2} 1200w, ${s52a3} 1600w`,
  },
  {
    src: s53,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s53f0} 480w, ${s53f1} 800w, ${s53f2} 1200w, ${s53f3} 1600w`,
    webpSrcSet: `${s53w0} 480w, ${s53w1} 800w, ${s53w2} 1200w, ${s53w3} 1600w`,
    avifSrcSet: `${s53a0} 480w, ${s53a1} 800w, ${s53a2} 1200w, ${s53a3} 1600w`,
  },
  {
    src: s54,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s54f0} 480w, ${s54f1} 800w, ${s54f2} 1067w`,
    webpSrcSet: `${s54w0} 480w, ${s54w1} 800w, ${s54w2} 1067w`,
    avifSrcSet: `${s54a0} 480w, ${s54a1} 800w, ${s54a2} 1067w`,
  },
  {
    src: s55,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s55f0} 480w, ${s55f1} 800w, ${s55f2} 1200w, ${s55f3} 1600w`,
    webpSrcSet: `${s55w0} 480w, ${s55w1} 800w, ${s55w2} 1200w, ${s55w3} 1600w`,
    avifSrcSet: `${s55a0} 480w, ${s55a1} 800w, ${s55a2} 1200w, ${s55a3} 1600w`,
  },
  {
    src: s56,
    width: 800,
    height: 871,
    fallbackSrcSet: `${s56f0} 800w`,
    webpSrcSet: `${s56w0} 480w, ${s56w1} 800w`,
    avifSrcSet: `${s56a0} 480w, ${s56a1} 800w`,
  },
  {
    src: s57,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s57f0} 480w, ${s57f1} 800w, ${s57f2} 1067w`,
    webpSrcSet: `${s57w0} 480w, ${s57w1} 800w, ${s57w2} 1067w`,
    avifSrcSet: `${s57a0} 480w, ${s57a1} 800w, ${s57a2} 1067w`,
  },
  {
    src: s58,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s58f0} 480w, ${s58f1} 800w, ${s58f2} 1200w, ${s58f3} 1600w`,
    webpSrcSet: `${s58w0} 480w, ${s58w1} 800w, ${s58w2} 1200w, ${s58w3} 1600w`,
    avifSrcSet: `${s58a0} 480w, ${s58a1} 800w, ${s58a2} 1200w, ${s58a3} 1600w`,
  },
  {
    src: s59,
    width: 1335,
    height: 1392,
    fallbackSrcSet: `${s59f0} 480w, ${s59f1} 800w, ${s59f2} 1200w, ${s59f3} 1335w`,
    webpSrcSet: `${s59w0} 480w, ${s59w1} 800w, ${s59w2} 1200w, ${s59w3} 1335w`,
    avifSrcSet: `${s59a0} 480w, ${s59a1} 800w, ${s59a2} 1200w, ${s59a3} 1335w`,
  },
  {
    src: s60,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s60f0} 480w, ${s60f1} 800w, ${s60f2} 1200w, ${s60f3} 1600w`,
    webpSrcSet: `${s60w0} 480w, ${s60w1} 800w, ${s60w2} 1200w, ${s60w3} 1600w`,
    avifSrcSet: `${s60a0} 480w, ${s60a1} 800w, ${s60a2} 1200w, ${s60a3} 1600w`,
  },
  {
    src: s61,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s61f0} 480w, ${s61f1} 800w, ${s61f2} 1200w, ${s61f3} 1600w`,
    webpSrcSet: `${s61w0} 480w, ${s61w1} 800w, ${s61w2} 1200w, ${s61w3} 1600w`,
    avifSrcSet: `${s61a0} 480w, ${s61a1} 800w, ${s61a2} 1200w, ${s61a3} 1600w`,
  },
  {
    src: s62,
    width: 1044,
    height: 1392,
    fallbackSrcSet: `${s62f0} 480w, ${s62f1} 800w, ${s62f2} 1044w`,
    webpSrcSet: `${s62w0} 480w, ${s62w1} 800w, ${s62w2} 1044w`,
    avifSrcSet: `${s62a0} 480w, ${s62a1} 800w, ${s62a2} 1044w`,
  },
  {
    src: s63,
    width: 1067,
    height: 1600,
    fallbackSrcSet: `${s63f0} 480w, ${s63f1} 800w, ${s63f2} 1067w`,
    webpSrcSet: `${s63w0} 480w, ${s63w1} 800w, ${s63w2} 1067w`,
    avifSrcSet: `${s63a0} 480w, ${s63a1} 800w, ${s63a2} 1067w`,
  },
  {
    src: s64,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s64f0} 480w, ${s64f1} 800w, ${s64f2} 1200w, ${s64f3} 1600w`,
    webpSrcSet: `${s64w0} 480w, ${s64w1} 800w, ${s64w2} 1200w, ${s64w3} 1600w`,
    avifSrcSet: `${s64a0} 480w, ${s64a1} 800w, ${s64a2} 1200w, ${s64a3} 1600w`,
  },
  {
    src: s65,
    width: 726,
    height: 800,
    fallbackSrcSet: `${s65f0} 726w`,
    webpSrcSet: `${s65w0} 480w, ${s65w1} 726w`,
    avifSrcSet: `${s65a0} 480w, ${s65a1} 726w`,
  },
  {
    src: s66,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s66f0} 480w, ${s66f1} 800w, ${s66f2} 1200w, ${s66f3} 1600w`,
    webpSrcSet: `${s66w0} 480w, ${s66w1} 800w, ${s66w2} 1200w, ${s66w3} 1600w`,
    avifSrcSet: `${s66a0} 480w, ${s66a1} 800w, ${s66a2} 1200w, ${s66a3} 1600w`,
  },
  {
    src: s67,
    width: 921,
    height: 968,
    fallbackSrcSet: `${s67f0} 921w`,
    webpSrcSet: `${s67w0} 480w, ${s67w1} 800w, ${s67w2} 921w`,
    avifSrcSet: `${s67a0} 480w, ${s67a1} 800w, ${s67a2} 921w`,
  },
  {
    src: s68,
    width: 960,
    height: 1080,
    fallbackSrcSet: `${s68f0} 960w`,
    webpSrcSet: `${s68w0} 480w, ${s68w1} 800w, ${s68w2} 960w`,
    avifSrcSet: `${s68a0} 480w, ${s68a1} 800w, ${s68a2} 960w`,
  },
  {
    src: s69,
    width: 759,
    height: 671,
    fallbackSrcSet: `${s69f0} 759w`,
    webpSrcSet: `${s69w0} 480w, ${s69w1} 759w`,
    avifSrcSet: `${s69a0} 480w, ${s69a1} 759w`,
  },
  {
    src: s70,
    width: 791,
    height: 892,
    fallbackSrcSet: `${s70f0} 791w`,
    webpSrcSet: `${s70w0} 480w, ${s70w1} 791w`,
    avifSrcSet: `${s70a0} 480w, ${s70a1} 791w`,
  },
  {
    src: s71,
    width: 1600,
    height: 1067,
    fallbackSrcSet: `${s71f0} 480w, ${s71f1} 800w, ${s71f2} 1200w, ${s71f3} 1600w`,
    webpSrcSet: `${s71w0} 480w, ${s71w1} 800w, ${s71w2} 1200w, ${s71w3} 1600w`,
    avifSrcSet: `${s71a0} 480w, ${s71a1} 800w, ${s71a2} 1200w, ${s71a3} 1600w`,
  },
  {
    src: s72,
    width: 500,
    height: 500,
    fallbackSrcSet: `${s72f0} 480w, ${s72f1} 500w`,
    webpSrcSet: `${s72w0} 480w, ${s72w1} 500w`,
    avifSrcSet: `${s72a0} 480w, ${s72a1} 500w`,
  },
  {
    src: s73,
    width: 500,
    height: 500,
    fallbackSrcSet: `${s73f0} 480w, ${s73f1} 500w`,
    webpSrcSet: `${s73w0} 480w, ${s73w1} 500w`,
    avifSrcSet: `${s73a0} 480w, ${s73a1} 500w`,
  },
  {
    src: s74,
    width: 500,
    height: 500,
    fallbackSrcSet: `${s74f0} 480w, ${s74f1} 500w`,
    webpSrcSet: `${s74w0} 480w, ${s74w1} 500w`,
    avifSrcSet: `${s74a0} 480w, ${s74a1} 500w`,
  },
  {
    src: s75,
    width: 600,
    height: 800,
    fallbackSrcSet: `${s75f0} 600w`,
    webpSrcSet: `${s75w0} 480w, ${s75w1} 600w`,
    avifSrcSet: `${s75a0} 480w, ${s75a1} 600w`,
  },
  {
    src: s76,
    width: 704,
    height: 699,
    fallbackSrcSet: `${s76f0} 704w`,
    webpSrcSet: `${s76w0} 480w, ${s76w1} 704w`,
    avifSrcSet: `${s76a0} 480w, ${s76a1} 704w`,
  },
];

registerResponsiveImages(records);

export const responsiveImageRecords = records;
